export const Tables = {
  Centers: "centers",
  Customers: "customers",
  CenterImages: "center_images",
  CenterStaff: "center_staff",
  Users: "users",
  Services: "services",
  Subservices: "subservices",
  SubserviceStaff: "subservice_staff",
  Schedules: "working_schedules",
  ScheduleBreaks: "work_breaks ",
  Reservations: "reservations",
  Subscriptions: "subscriptions",
  Orders: "customer_orders",
};
